"""
quality_core.rca

Root Cause Analysis (RCA) suite: schema definitions, validation boundaries,
and domain models for 5-Why problem solving, 6M Fishbone cause-and-effect
diagrams, Kepner-Tregoe Is/Is-Not scoping matrices, and the 8D report with its
nine disciplines, its deterministic state machine and gate engine, and the
D0/D1/D2/D3 discipline engines.
"""

from __future__ import annotations

from quality_core.rca.eight_d import (
    EightDState,
    EightDTransitionResult,
    GateCode,
    TransitionReason,
    TransitionVerdict,
    transition_eight_d,
)
from quality_core.rca.eight_d_disciplines import (
    D0Finding,
    D0ValidationResult,
    D1Finding,
    D1ValidationResult,
    D2Finding,
    D2ValidationResult,
    D3Finding,
    D3ValidationResult,
    validate_d0_readiness,
    validate_d1_team,
    validate_d2_problem_description,
    validate_d3_containment,
)
from quality_core.rca.eight_d_schema import (
    CONTAINMENT_ACTION_SCHEMA,
    CORRECTIVE_ACTION_CANDIDATE_SCHEMA,
    DOCUMENTATION_UPDATE_SCHEMA,
    TEAM_MEMBER_SCHEMA,
    CandidateCauseTest,
    ContainmentAction,
    ContainmentActionList,
    CorrectiveActionCandidate,
    CorrectiveActionCandidateList,
    D0Discipline,
    D1Discipline,
    D2Discipline,
    D3Discipline,
    D4Discipline,
    D5Discipline,
    D6Discipline,
    D7Discipline,
    D8Discipline,
    DocumentationUpdate,
    DocumentationUpdateList,
    EffectivenessVerification,
    EightDDiscipline,
    EightDReport,
    EightDStatus,
    EscapePointFinding,
    FiveWhyLegType,
    FiveWhyVerdict,
    ImplementedAction,
    LinkedNCRValidation,
    RootCauseFinding,
    TeamMember,
    TeamMemberList,
    WarningOverride,
    load_containment_actions_csv,
    load_corrective_action_candidates_csv,
    load_documentation_updates_csv,
    load_eight_d_json,
    load_eight_d_json_from_path,
    load_team_members_csv,
    validate_containment_actions,
    validate_corrective_action_candidates,
    validate_documentation_updates,
    validate_eight_d,
    validate_team_members,
)
from quality_core.rca.export import (
    FISHBONE_COLUMN_WIDTHS,
    FISHBONE_EXPORT_COLUMNS,
    FISHBONE_SHEET_TITLE,
    FIVE_WHY_COLUMN_WIDTHS,
    FIVE_WHY_EXPORT_COLUMNS,
    FIVE_WHY_SHEET_TITLE,
    IS_IS_NOT_COLUMN_WIDTHS,
    IS_IS_NOT_EXPORT_COLUMNS,
    IS_IS_NOT_SHEET_TITLE,
    benchmark_fishbone_dataset,
    benchmark_five_why_chain,
    benchmark_is_is_not_matrix,
    benchmark_rca_datasets,
    build_rca_workbook,
    export_fishbone_workbook,
    export_five_why_workbook,
    export_is_is_not_workbook,
    export_rca_workbook,
)
from quality_core.rca.fishbone import (
    FishboneCategorizationResult,
    categorize_fishbone,
)
from quality_core.rca.five_why import (
    AntiPatternFinding,
    FiveWhyLinkEval,
    FiveWhyValidationResult,
    SystemicAssessment,
    validate_five_why_chain,
)
from quality_core.rca.is_is_not import (
    CandidateCause,
    IsIsNotScopingResult,
    scope_is_is_not,
)
from quality_core.rca.schema import (
    FISHBONE_SCHEMA,
    FIVE_WHY_SCHEMA,
    IS_IS_NOT_SCHEMA,
    Category6M,
    FishboneCause,
    FishboneDataset,
    FiveWhyChain,
    FiveWhyStep,
    IngestError,
    IsIsNotMatrix,
    IsIsNotRow,
    KTDimension,
    load_fishbone_csv,
    load_five_why_csv,
    load_is_is_not_csv,
    validate_fishbone,
    validate_five_why,
    validate_is_is_not,
)

__all__ = [
    # 8D
    "CONTAINMENT_ACTION_SCHEMA",
    "CORRECTIVE_ACTION_CANDIDATE_SCHEMA",
    "CandidateCauseTest",
    "ContainmentAction",
    "ContainmentActionList",
    "CorrectiveActionCandidate",
    "CorrectiveActionCandidateList",
    "D0Discipline",
    "D0Finding",
    "D0ValidationResult",
    "D1Discipline",
    "D1Finding",
    "D1ValidationResult",
    "D2Discipline",
    "D2Finding",
    "D2ValidationResult",
    "D3Discipline",
    "D3Finding",
    "D3ValidationResult",
    "D4Discipline",
    "D5Discipline",
    "D6Discipline",
    "D7Discipline",
    "D8Discipline",
    "DOCUMENTATION_UPDATE_SCHEMA",
    "DocumentationUpdate",
    "DocumentationUpdateList",
    "EffectivenessVerification",
    "EightDDiscipline",
    "EightDReport",
    "EightDState",
    "EightDTransitionResult",
    "EightDStatus",
    "EscapePointFinding",
    "FiveWhyLegType",
    "FiveWhyVerdict",
    "GateCode",
    "ImplementedAction",
    "LinkedNCRValidation",
    "RootCauseFinding",
    "TEAM_MEMBER_SCHEMA",
    "TeamMember",
    "TeamMemberList",
    "TransitionReason",
    "TransitionVerdict",
    "WarningOverride",
    "load_containment_actions_csv",
    "load_corrective_action_candidates_csv",
    "load_documentation_updates_csv",
    "load_eight_d_json",
    "load_eight_d_json_from_path",
    "load_team_members_csv",
    "validate_containment_actions",
    "validate_corrective_action_candidates",
    "validate_d0_readiness",
    "validate_d1_team",
    "validate_d2_problem_description",
    "validate_d3_containment",
    "validate_documentation_updates",
    "validate_eight_d",
    "validate_team_members",
    "transition_eight_d",
    # 5-Why
    "AntiPatternFinding",
    "FIVE_WHY_COLUMN_WIDTHS",
    "FIVE_WHY_EXPORT_COLUMNS",
    "FIVE_WHY_SCHEMA",
    "FIVE_WHY_SHEET_TITLE",
    "FiveWhyChain",
    "FiveWhyLinkEval",
    "FiveWhyStep",
    "FiveWhyValidationResult",
    "SystemicAssessment",
    "benchmark_five_why_chain",
    "export_five_why_workbook",
    "load_five_why_csv",
    "validate_five_why",
    "validate_five_why_chain",
    # Fishbone
    "Category6M",
    "FISHBONE_COLUMN_WIDTHS",
    "FISHBONE_EXPORT_COLUMNS",
    "FISHBONE_SCHEMA",
    "FISHBONE_SHEET_TITLE",
    "FishboneCategorizationResult",
    "FishboneCause",
    "FishboneDataset",
    "benchmark_fishbone_dataset",
    "categorize_fishbone",
    "export_fishbone_workbook",
    "load_fishbone_csv",
    "validate_fishbone",
    # Is/Is-Not
    "CandidateCause",
    "IS_IS_NOT_COLUMN_WIDTHS",
    "IS_IS_NOT_EXPORT_COLUMNS",
    "IS_IS_NOT_SCHEMA",
    "IS_IS_NOT_SHEET_TITLE",
    "IsIsNotMatrix",
    "IsIsNotRow",
    "IsIsNotScopingResult",
    "KTDimension",
    "benchmark_is_is_not_matrix",
    "export_is_is_not_workbook",
    "load_is_is_not_csv",
    "scope_is_is_not",
    "validate_is_is_not",
    # Combined RCA Exporters & Benchmarks
    "benchmark_rca_datasets",
    "build_rca_workbook",
    "export_rca_workbook",
    # Error
    "IngestError",
]
