"""
Production Part Approval Process (PPAP) Core Engine — deterministic 18-element auditor,
Table 4.1 submission/retention matrix, applicability rules, PSW field validator,
and cross-engine linkage.
"""

from __future__ import annotations

from quality_core.ppap.schema import (
    EVIDENCE_STATUS_ALIASES,
    EVIDENCE_STATUS_VALUES,
    PPAP_ELEMENT_ALIASES,
    PPAP_ELEMENT_IDS,
    PPAP_ELEMENT_NAMES,
    PPAP_ELEMENT_NUMBERS,
    PPAP_PACKAGE_SCHEMA,
    REASON_FOR_SUBMISSION_ALIASES,
    REASON_FOR_SUBMISSION_VALUES,
    SUBMISSION_LEVEL_ALIASES,
    SUBMISSION_LEVEL_DESCRIPTIONS,
    SUBMISSION_LEVELS,
    EvidenceItem,
    EvidenceStatus,
    IngestError,
    PPAPElementId,
    PPAPPackage,
    ReasonForSubmission,
    SubmissionLevel,
    load_ppap_csv,
    validate_ppap,
)
from quality_core.ppap.table_4_1 import (
    ELEMENT_IDS,
    REQUIREMENT_CODES,
    TABLE_4_1_LEGEND,
    TABLE_4_1_MATRIX,
    RequirementCode,
    elements_required_at_level,
    lookup_requirement,
    requirement_legend,
    submission_level_description,
)

__all__ = [
    "ELEMENT_IDS",
    "EVIDENCE_STATUS_ALIASES",
    "EVIDENCE_STATUS_VALUES",
    "EvidenceItem",
    "EvidenceStatus",
    "IngestError",
    "PPAPElementId",
    "PPAPPackage",
    "PPAP_ELEMENT_ALIASES",
    "PPAP_ELEMENT_IDS",
    "PPAP_ELEMENT_NAMES",
    "PPAP_ELEMENT_NUMBERS",
    "PPAP_PACKAGE_SCHEMA",
    "REASON_FOR_SUBMISSION_ALIASES",
    "REASON_FOR_SUBMISSION_VALUES",
    "REQUIREMENT_CODES",
    "ReasonForSubmission",
    "RequirementCode",
    "SUBMISSION_LEVELS",
    "SUBMISSION_LEVEL_ALIASES",
    "SUBMISSION_LEVEL_DESCRIPTIONS",
    "SubmissionLevel",
    "TABLE_4_1_LEGEND",
    "TABLE_4_1_MATRIX",
    "elements_required_at_level",
    "load_ppap_csv",
    "lookup_requirement",
    "requirement_legend",
    "submission_level_description",
    "validate_ppap",
]
